---
# TODO: SETUP THIS AS I HAVE NO IDEA WHAT I'M DOING...
agimus_controller_node:
  ros__parameters:
    ocp:
      dt: 0.01
      horizon_size: 30
      dt_factor_n_seq:
        n_steps: [20, 10]
        factors: [1, 2]
      armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      max_qp_iter: 200
      max_iter: 4
      activate_callback: false
    publish_debug_data: true
    constant_delay: false
    rate: 100.0
    free_flyer: false
    collision_as_capsule: false
    self_collision: false
    collision_pairs_names: [cp_1]
    cp_1:
      first: arm_right_7_link_0
      second: arm_left_7_link_0
